version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "platform-kms"
# s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-8qhe1payfv0l"
# s3_prefix = "platform-kms"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev\""
image_repositories = []
