AWSTemplateFormatVersion: '2010-09-09'

Description: >
  KMS resources used by the Authentication Account Management (AAM) application.

Parameters:
  Environment:
    Description: "The name of the environment to deploy to"
    Type: "String"
    Default: build
    AllowedValues:
      - "dev"
      - "build"
      - "staging"
      - "integration"
      - "production"
  CodeSigningConfigArn:
    Type: String
    Description: >
      The ARN of the Code Signing Config to use, provided by the deployment pipeline
    Default: "none"

  PermissionsBoundary:
    Type: String
    Description: >
      The ARN of the permissions boundary to apply to any role created by the template
    Default: "none"

Conditions:
  UseCodeSigning:
    Fn::Not:
      - Fn::Equals:
          - !Ref CodeSigningConfigArn
          - "none"

  UsePermissionsBoundary:
    Fn::Not:
      - Fn::Equals:
          - !Ref PermissionsBoundary
          - "none"

Resources:
  AAMKMSSigningKey:
    Type: AWS::KMS::Key
    #checkov:skip=CKV_AWS_7:Ensure rotation for customer created CMKs is enabled
#    DeletionPolicy: Retain
#    UpdateReplacePolicy: Retain
    Properties:
      Description: KMS signing key for Authentication Account Management (AAM) JWT Authentication
      Enabled: true
      EnableKeyRotation: false
      KeySpec: RSA_2048
      KeyUsage: SIGN_VERIFY
      MultiRegion: false
      PendingWindowInDays: 30
      KeyPolicy:
        Version: "2012-10-17"
        Statement:
        - Effect: Allow
          Principal:
            AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
          Action:
            - 'kms:Create*'
            - 'kms:Describe*'
            - 'kms:Enable*'
            - 'kms:List*'
            - 'kms:Put*'
            - 'kms:Update*'
            - 'kms:Revoke*'
            - 'kms:Disable*'
            - 'kms:Get*'
            - 'kms:Delete*'
            - 'kms:ScheduleKeyDeletion'
            - 'kms:CancelKeyDeletion'
          Resource:
          - "*"
# Create a non-root user that has access to KMS policy
#        Effect: Allow
#        Principal:
#          AWS: 'arn:aws:iam::${AWS::AccountId}:role/ExecutionRole'
#        Action:
#          - 'kms:Sign'
#          - 'kms:Verify'
#          - 'kms:DescribeKey'
#        Resource: '*'

      Tags:
        - Key: Product
          Value: GOV.UK Sign In
        - Key: System
          Value: Accounts
        - Key: Environment
          Value: !Ref Environment
        - Key: Name
          Value: !Sub "${AWS::StackName}-AAMKMSSigningKey"
        - Key: Owner
          Value: govuk-accounts-tech@digital.cabinet-office.gov.uk
        - Key: Source
          Value: alphagov/di-accounts-infra/account-management-kms/template.yaml
        - Key: Application
          Value: Authentication Account Management
        - Key: CheckovRulesToSkip
          Value: CKV_AWS_7

  AAMKMSSigningKeyAlias:
    Type: 'AWS::KMS::Alias'
    Properties:
      AliasName: !Sub "alias/${Environment}-aam-signing-key"
      TargetKeyId: !Ref AAMKMSSigningKey

  AAMKMSSigningKeySSM:
    Type: AWS::SSM::Parameter
    Properties:
      Description: The ARN of the AAM Signing Key
      Name: !Sub "/${Environment}/${AWS::StackName}/KMS/SigningKeyArn"
      Type: String
      Value: !GetAtt AAMKMSSigningKey.Arn

  AAMKMSSigningKeyIdSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Description: The Id of the AAM Signing Key
      Name: !Sub "/${Environment}/${AWS::StackName}/KMS/SigningKeyId"
      Type: String
      Value: !Ref AAMKMSSigningKey
  AAMKMSSigningKeyAliasSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Description: The Alias of the AAM Signing Key
      Name: !Sub "/${Environment}/${AWS::StackName}/KMS/SigningKeyAlias"
      Type: String
      Value: !Ref AAMKMSSigningKeyAlias

Outputs:
  AAMSigningKeyArn:
    Description: "The ARN of the AAM Signing key"
    Value: !GetAtt AAMKMSSigningKey.Arn
    Export:
      Name: !Sub "${AWS::StackName}-signing-key-arn"
  AAMSigningKeyId:
    Description: "The Id of the AAM Signing key"
    Value: !Ref AAMKMSSigningKey
    Export:
      Name: !Sub "${AWS::StackName}-signing-key-id"
  AAMSigningKeyAlias:
    Description: "The Alias of the AAM Signing key"
    Value: !Ref AAMKMSSigningKeyAlias
