AWSTemplateFormatVersion: '2010-09-09'

Description: >
  This template contains IAM permissions for access that's not specific to an application.
  It should not be used for managing developer access.

Parameters:
  Environment:
    Description: The name of the environment to deploy to
    Type: String
    Default: dev
    AllowedValues:
      - "dev"
      - "build"
      - "staging"
      - "integration"
      - "production"

Resources:
