AWSTemplateFormatVersion: "2010-09-09"

Description: >
  Stack to create an SNS topic with external API subscriptions such as PagerDuty

Outputs:
  AlertNotificationTopicArn:
    Description: >
      The ARN of the SNS topic with external API subscriptions such as PagerDuty
    Value: !Ref AlertNotificationTopic
    Export:
      Name: !Sub "${AWS::StackName}-AlertNotificationTopicArn"

  AlertNotificationTopicKey:
    Description: >
      The ARN of the SNS topic data encryption key
    Value: !GetAtt AlertNotificationTopicKey.Arn
    Export:
      Name: !Sub "${AWS::StackName}-AlertNotificationTopicKey"

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Alerting Integration"
        Parameters:
          - SubscriptionEndpoint

Parameters:
  SubscriptionEndpoint:
    Description: >
      External API subscription endpoint i.e. PagerDuty events integration API
    Type: String
    Default: "none"
    AllowedPattern: "(^https://.+)|(none)"
    ConstraintDescription: "Must be a URL of format (https://.*) or leave as 'none'"

Conditions:
  CreateSNSSubscription:
    Fn::Not:
      - Fn::Equals:
          - !Ref SubscriptionEndpoint
          - "none"

Resources:
  AlertNotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      KmsMasterKeyId: !Ref AlertNotificationTopicKey
      Tags:
        - Key: Name
          Value: !Join
            - "-"
            - - !Ref AWS::StackName
              - "AlertNotificationTopic"
        - Key: Service
          Value: "ci/cd"
        - Key: Source
          Value: "alphagov/di-devplatform-deploy/alerting-integration/template.yaml"

  AlertNotificationTopicKey:
    Type: AWS::KMS::Key
    Properties:
      EnableKeyRotation: true
      KeyPolicy:
        Version: 2012-10-17
        Statement:
          - Sid: "Allow the account to manage the key"
            Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action:
              - "kms:*"
            Resource:
              - "*"
          - Sid: "Allow Cloudwatch alerts access"
            Effect: Allow
            Principal:
              Service: cloudwatch.amazonaws.com
            Action:
              - "kms:Encrypt*"
              - "kms:Decrypt*"
              - "kms:ReEncrypt*"
              - "kms:GenerateDataKey*"
              - "kms:Describe*"
            Resource:
              - "*"
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-AlertNotificationTopicKey"
        - Key: Service
          Value: "ci/cd"
        - Key: Source
          Value: "alphagov/di-devplatform-deploy/alerting-integration/template.yaml"

  AlertNotificationTopicSubscription:
    Condition: CreateSNSSubscription
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !Ref SubscriptionEndpoint
      Protocol: 'https'
      TopicArn: !Ref AlertNotificationTopic
