AWSTemplateFormatVersion: "2010-09-09"

Description: Build notifications

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Build notifications"
        Parameters:
          - SlackWorkspaceId
          - SlackChannelId

Parameters:
  SlackWorkspaceId:
    Description: >
      The ID of the Slack workspace where build notification messages are
      posted. This is retrieved from the AWS Chatbot integration.
    Type: String
    Default: "T8GT9416G"
    AllowedPattern: "\\w+"
    ConstraintDescription: "must be an AWS Chatbot Slack workspace ID"

  SlackChannelId:
    Description: >
      The ID of the Slack channel where build notification messages are posted.
      This is taken from the channel details in Slack.
    Type: String
    AllowedPattern: "\\w+"
    ConstraintDescription: "must be a Slack channel ID"

Outputs:
  BuildNotificationTopicArn:
    Description: >
      The ARN of the SNS topic that receives CodePipeline build notifications that gets sent to Slack.
    Value: !Ref BuildNotificationTopic
    Export:
      Name: !Sub "${AWS::StackName}-BuildNotificationTopicArn"

Resources:
  BuildNotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      KmsMasterKeyId: !Ref BuildNotificationTopicKey
      Tags:
        - Key: Name
          Value: !Join
            - "-"
            - - !Ref AWS::StackName
              - "BuildNotificationTopic"
        - Key: Service
          Value: "ci/cd"
        - Key: Source
          Value: "alphagov/di-devplatform-deploy/build-notifications/template.yaml"

  BuildNotificationTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - !Ref BuildNotificationTopic
      PolicyDocument:
        Statement:
          - Action: "sns:Publish"
            Effect: Allow
            Resource: !Ref BuildNotificationTopic
            Principal:
              Service: codestar-notifications.amazonaws.com

  BuildNotificationTopicKey:
    Type: AWS::KMS::Key
    Properties:
      EnableKeyRotation: true
      KeyPolicy:
        Version: 2012-10-17
        Statement:
          - Sid: "Allow CodeStar Notifications to enqueue encrypted messages"
            Effect: Allow
            Resource: "*"
            Action:
              - "kms:Decrypt"
              - "kms:GenerateDataKey"
            Principal:
              Service: "codestar-notifications.amazonaws.com"
          - Sid: "Allow the account to manage the key"
            Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action: "kms:*"
            Resource: "*"
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-BuildNotificationTopicKey"
        - Key: Service
          Value: "ci/cd"
        - Key: Source
          Value: "alphagov/di-devplatform-deploy/build-notifications/template.yaml"

  CodeStarNotificationsServiceLinkedRole:
    Type: AWS::IAM::ServiceLinkedRole
    DeletionPolicy: Retain
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
            - W3011  # The UpdateReplacePolicy does not apply to this resource
    Properties:
      AWSServiceName: codestar-notifications.amazonaws.com

  ChatbotRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "chatbot.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Tags:
        - Key: Name
          Value: !Join
            - "-"
            - - !Ref AWS::StackName
              - "ChatbotRole"
        - Key: Service
          Value: "ci/cd"
        - Key: Source
          Value: "alphagov/di-devplatform-deploy/build-notifications/template.yaml"

  ChatbotChannelConfiguration:
    Type: AWS::Chatbot::SlackChannelConfiguration
    DependsOn: ChatbotServiceLinkedRole
    Properties:
      ConfigurationName: !Sub "${AWS::StackName}-build-notifications"
      IamRoleArn: !GetAtt ChatbotRole.Arn
      SlackChannelId: !Ref SlackChannelId
      SlackWorkspaceId: !Ref SlackWorkspaceId
      SnsTopicArns:
        - !Ref BuildNotificationTopic

  ChatbotServiceLinkedRole:
    Type: AWS::IAM::ServiceLinkedRole
    DeletionPolicy: Retain
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
            - W3011  # The UpdateReplacePolicy does not apply to this resource
    Properties:
      AWSServiceName: management.chatbot.amazonaws.com