AWSTemplateFormatVersion: "2010-09-09"

Description: >-
  Creates the necessary components to manage DNS in Accounts.

Parameters:
  Environment:
    Description: The name of the environment to deploy to
    Type: String
    AllowedValues:
      - dev
      - build
      - staging
      - integration
      - production

Mappings:
  PlatformConfiguration:
    dev:
      home: home.dev.account.gov.uk
    build:
      home: home.build.account.gov.uk
    staging:
      home: home.staging.account.gov.uk
    integration:
      home: home.integration.account.gov.uk
    production:
      home: home.account.gov.uk

Resources:

  HomeDomainCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Sub
        - "${DNSSUFFIX}"
        - DNSSUFFIX: !FindInMap [ PlatformConfiguration, !Ref Environment, home ]
      SubjectAlternativeNames:
        - !Sub
          - "*.${DNSSUFFIX}"
          - DNSSUFFIX: !FindInMap [ PlatformConfiguration, !Ref Environment, home ]
      DomainValidationOptions:
        - DomainName: !Sub
            - "${DNSSUFFIX}"
            - DNSSUFFIX: !FindInMap [ PlatformConfiguration, !Ref Environment, home ]
          HostedZoneId: !ImportValue HomeHostedZoneId
      ValidationMethod: DNS

  HomeCertificateARNSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Description: The Home Domain Certificate ARN
      Name: !Sub "/${Environment}/Platform/ACM/HostedZone/Certificate/Home/ARN"
      Type: String
      Value: !Ref HomeDomainCertificate
      Tags:
        VPC: !Sub ${AWS::StackName}
