AWSTemplateFormatVersion: '2010-09-09'

Description: >
  An ECS Cluster.

Parameters:
  Environment:
    Description: "The name of the environment to deploy to"
    Type: "String"
    Default: build
    AllowedValues:
      - "dev"
      - "build"
      - "staging"
      - "integration"
      - "production"
  CodeSigningConfigArn:
    Type: String
    Description: >
      The ARN of the Code Signing Config to use, provided by the deployment pipeline
    Default: "none"

  PermissionsBoundary:
    Type: String
    Description: >
      The ARN of the permissions boundary to apply to any role created by the template
    Default: "none"

Conditions:
  UseCodeSigning:
    Fn::Not:
      - Fn::Equals:
          - !Ref CodeSigningConfigArn
          - "none"

  UsePermissionsBoundary:
    Fn::Not:
      - Fn::Equals:
          - !Ref PermissionsBoundary
          - "none"

Resources:

  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub ${Environment}-accounts-ecs-cluster
      CapacityProviders:
        - FARGATE
      ClusterSettings:
        - Name: containerInsights
          Value: enabled
      Tags:
        - Key: Product
          Value: GOV.UK Sign In
        - Key: System
          Value: Accounts
        - Key: Environment
          Value: !Ref Environment
        - Key: Name
          Value: !Sub "${AWS::StackName}-accounts-ecs-cluster"
        - Key: Owner
          Value: govuk-accounts-tech@digital.cabinet-office.gov.uk
        - Key: Source
          Value: alphagov/di-accounts-infra/shared-ecs/template.yaml
        - Key: Application
          Value: Shared

  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${Environment}-accounts-ecs-cluster-role
      Path: !Sub /${Environment}/accounts/ecs/cluster-role/
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: [ecs-tasks.amazonaws.com]
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy'
      Tags:
        - Key: Product
          Value: GOV.UK Sign In
        - Key: System
          Value: Accounts
        - Key: Environment
          Value: !Ref Environment
        - Key: Owner
          Value: govuk-accounts-tech@digital.cabinet-office.gov.uk
        - Key: Source
          Value: alphagov/di-accounts-infra/shared-ecs/template.yaml
        - Key: Application
          Value: Shared

  ECSClusterNameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: The name of the ECS cluster
      Name: !Sub "/${Environment}/${AWS::StackName}/ECS/Cluster"
      Type: String
      Value: !Ref ECSCluster
      Tags:
        - Key: Product
          Value: GOV.UK Sign In
        - Key: System
          Value: Accounts
        - Key: Environment
          Value: !Ref Environment
        - Key: Owner
          Value: govuk-accounts-tech@digital.cabinet-office.gov.uk
        - Key: Source
          Value: alphagov/di-accounts-infra/shared-ecs/template.yaml
        - Key: Application
          Value: Shared
Outputs:

  ECSCluster:
    Description: A reference to the ECS cluster
    Value: !Ref ECSCluster
    Export:
      Name: !Sub "${Environment}-accounts-ecs-cluster"

  ExecutionRole:
    Description: A reference to ECS Cluster Role
    Value: !GetAtt   ExecutionRole.Arn
    Export:
      Name: !Sub "${Environment}-accounts-ecs-cluster-role"
