AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: Mocks that should only be created once in the development and build environments.

Parameters:
  Environment:
    Description: The name of the environment to deploy to
    Type: String
    Default: dev
    AllowedValues:
      - "dev"
      - "build"
  ProductTagValue:
    Description: Value for the Product Tag
    Type: String
    Default: GOV.UK Sign In
  SystemTagValue:
    Description: Value for the System Tag
    Type: String
    Default: Accounts
  OwnerTagValue:
    Description: Value for the Owner Tag
    Type: String
    Default: govuk-accounts-tech@digital.cabinet-office.gov.uk
  SourceTagValue:
    Description: Value for the Source Tag
    Type: String
    Default: alphagov/di-accounts-infra/mocks/template.yaml

Resources:
  MockPublishingAPI:
    Type: AWS::Serverless::Api
    Properties:
      MethodSettings:
        - LoggingLevel: INFO
          ResourcePath: '/*'
          HttpMethod: '*'
          DataTraceEnabled: true
          MetricsEnabled: true
          ThrottlingRateLimit: 500
          ThrottlingBurstLimit: 1000
      AccessLogSetting:
        DestinationArn: !GetAtt MockPublishingAPIAccessLogGroup.Arn
        Format: '{ "requestTime":"$context.requestTime", "requestId":"$context.requestId", "httpMethod":"$context.httpMethod", "path": "$context.path", "resourcePath":"$context.resourcePath", "status":"$context.status", "responseLength":"$context.responseLength", "responseLatency": $context.responseLatency, "xrayTraceId": "$context.xrayTraceId", "ip": "$context.identity.sourceIp", "caller":"$context.identity.caller", "user":"$context.identity.user" }'
      TracingEnabled: true
      Name: !Sub "/${Environment}/MockPublishingAPI"
      StageName: !Ref Environment
      OpenApiVersion: 3.0.1
      DefinitionBody:
        openapi: "3.0.1"
        info:
          version: "1.0"
          title: "Mock Publishing Service"
          description: A mock endpoint for the Publishing Service

        x-amazon-apigateway-request-validators:
          all:
            validateRequestBody: true
            validateRequestParameters: true
          params-only:
            validateRequestBody: true
            validateRequestParameters: true
        x-amazon-apigateway-request-validator: params-only

        paths:
          api/oidc-users/{subject-identifier}:
            put:
              requestBody:
                description: The request body
                required: true
                content:
                  application/json:
                    schema:
                      type: object
                      properties:
                        email:
                          type: string
                          format: email
                      required:
                        - email
              parameters:
                - in: path
                  name: subject-identifier
                  description: The subject identifier of the user to update
                  required: true
                  schema:
                    type: string
              responses:
                "200":
                  description: OK
                  content:
                    application/json:
                      schema:
                        properties:
                          sub:
                            type: string
                          email:
                            type: string
                            format: email
                          email_verified:
                            type: boolean
                        required:
                          - sub
                          - email
                          - email_verified
              x-amazon-apigateway-integration:
                httpMethod: PUT
                responses:
                  default:
                    statusCode: "200"
                    responseTemplates:
                      application/json: >
                        #set($body = $context.requestOverride.path.body)
                        { "sub": "$input.params().path.subject-identifier", "email": "$util.parseJson($body).email", "email_verified": true }
                requestTemplates:
                  application/json: >
                    #set($context.requestOverride.path.body = $input.body)
                    {
                        "statusCode": 200
                    }
                passthroughBehavior: never
                type: mock
            delete:
              parameters:
                - in: path
                  name: subject-identifier
                  schema:
                    type: string
                  required: true
                  description: The subject identifier of the user to delete
              responses:
                "204":
                  description: No Content
              x-amazon-apigateway-integration:
                httpMethod: DELETE
                responses:
                  default:
                    statusCode: "204"
                requestTemplates:
                  application/json: >
                    {
                        "statusCode": 204
                    }
                passthroughBehavior: never
                type: mock
      EndpointConfiguration:
        Type: REGIONAL
      Tags:
        Product: !Ref ProductTagValue
        System: !Ref SystemTagValue
        Environment: !Ref Environment
        Owner: !Ref OwnerTagValue
        Source: !Ref SourceTagValue

  MockPublishingAPIAccessLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/apigateway/mock-publishing-api-access-logs/${Environment}"
      RetentionInDays: 30
      Tags:
        - Key: Product
          Value: !Ref ProductTagValue
        - Key: System
          Value: !Ref SystemTagValue
        - Key: Environment
          Value: !Ref Environment
        - Key: Owner
          Value: !Ref OwnerTagValue
        - Key: Source
          Value: !Ref SourceTagValue

  MockPublishingAPIEndpointParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: The HTTP URL of the mock Publishing API
      Name: !Sub "/${Environment}/APIGateway/MockPublishingAPI/Endpoint"
      Type: String
      Value: !Sub "https://${MockPublishingAPI}.execute-api.${AWS::Region}.amazonaws.com/${Environment}"
      Tags:
        Product: !Ref ProductTagValue
        System: !Ref SystemTagValue
        Environment: !Ref Environment
        Owner: !Ref OwnerTagValue
        Source: !Ref SourceTagValue

Outputs:
  MockPublishingAPIEndpoint:
    Description: The HTTP URL of the mock Publishing API
    Value: !Sub "https://${MockPublishingAPI}.execute-api.${AWS::Region}.amazonaws.com/${Environment}"
