AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: Mocks that should only be created once in the development and build environments.

Parameters:
  Environment:
    Description: The name of the environment to deploy to
    Type: String
    Default: dev
    AllowedValues:
      - "dev"
      - "build"
  VpcStackName:
    Description: The name of the stack that defines the VPC
    Type: String
    Default: "vpc-enhanced"
  ProductTagValue:
    Description: Value for the Product Tag
    Type: String
    Default: GOV.UK Sign In
  SystemTagValue:
    Description: Value for the System Tag
    Type: String
    Default: Accounts
  OwnerTagValue:
    Description: Value for the Owner Tag
    Type: String
    Default: govuk-accounts-tech@digital.cabinet-office.gov.uk
  SourceTagValue:
    Description: Value for the Source Tag
    Type: String
    Default: alphagov/di-accounts-infra/mocks/template.yaml

Resources:
  MockPublishingAPI:
    Type: AWS::Serverless::Api
    Properties:
      # checkov:skip=CKV_AWS_120: Ensure API Gateway caching is enabled
      MethodSettings:
        - LoggingLevel: INFO
          ResourcePath: '/*'
          HttpMethod: '*'
          DataTraceEnabled: true
          MetricsEnabled: true
          ThrottlingRateLimit: 500
          ThrottlingBurstLimit: 1000
      AccessLogSetting:
        DestinationArn: !GetAtt MockPublishingAPIAccessLogGroup.Arn
        Format: '{ "requestTime":"$context.requestTime", "requestId":"$context.requestId", "httpMethod":"$context.httpMethod", "path": "$context.path", "resourcePath":"$context.resourcePath", "status":"$context.status", "responseLength":"$context.responseLength", "responseLatency": $context.responseLatency, "xrayTraceId": "$context.xrayTraceId", "ip": "$context.identity.sourceIp", "caller":"$context.identity.caller", "user":"$context.identity.user" }'
      TracingEnabled: true
      Name: mock-publishing-api
      StageName: !Ref Environment
      OpenApiVersion: 3.0.1
      DefinitionBody:
        openapi: "3.0.1"
        info:
          version: "1.0"
          title: "Mock Publishing Service"
          description: A mock endpoint for the Publishing Service

        x-amazon-apigateway-request-validators:
          all:
            validateRequestBody: true
            validateRequestParameters: true
          params-only:
            validateRequestBody: true
            validateRequestParameters: true
        x-amazon-apigateway-request-validator: params-only

        paths:
          api/oidc-users/{subject-identifier}:
            put:
              description: >
                Update an account and its email subscriptions by subject identifier
              parameters:
                - in: path
                  name: subject-identifier
                  description: The subject identifier of the user to update
                  required: true
                  schema:
                    type: string
                    additionalProperties: false
              requestBody:
                required: true
                content:
                  application/json:
                    schema:
                      type: object
                      additionalProperties: false
                      properties:
                        email:
                          type: string
                          format: email
                        email_verified:
                          type: boolean
                        has_unconfirmed_email:
                          type: boolean
                        legacy_sub:
                          type: string
#                      required:
#                        - email
#                        - email_verified
#                        - has_unconfirmed_email
#                        - legacy_sub
              responses:
                "200":
                  description: OK
                  content:
                    application/json:
                      schema:
                        type: object
                        additionalProperties: false
                        properties:
                          sub:
                            type: string
                          email:
                            type: string
                            format: email
                          email_verified:
                            type: boolean
                        required:
                          - sub
                          - email
                          - email_verified
              x-amazon-apigateway-integration:
#                connectionId:
#                  Fn::ImportValue:
#                    !Sub "${VpcStackName}-VpcLinkId"
#                connectionType: VPC_LINK
                httpMethod: PUT
                responses:
                  default:
                    statusCode: "200"
                    responseTemplates:
                      application/json: >
                        #set($body = $context.requestOverride.path.body)
                        { "sub": "$input.params().path.subject-identifier", "email": "$util.parseJson($body).email", "email_verified": "$util.parseJson($body).email_verified" }
                requestTemplates:
                  application/json: >
                    #set($context.requestOverride.path.body = $input.body)
                    {
                        "statusCode": 200
                    }
                passthroughBehavior: when_no_match
                type: mock
            delete:
              decription: >
                Delete an account by subject identifier
              parameters:
                - in: query
                  name: legacy_sub
                  description: If this is a user created pre-migration, their original subject identifier
                  required: false
                  schema:
                    type: string
                    additionalProperties: false
                - in: path
                  name: subject-identifier
                  description: The subject identifier of the user to delete
                  required: true
                  schema:
                    type: string
                    additionalProperties: false
              responses:
                "204":
                  description: No Content
              x-amazon-apigateway-integration:
#                connectionId:
#                  Fn::ImportValue:
#                    !Sub "${VpcStackName}-VpcLinkId"
#                connectionType: VPC_LINK
                httpMethod: DELETE
                responses:
                  default:
                    statusCode: "204"
                requestTemplates:
                  application/json: >
                    {
                        "statusCode": 204
                    }
                passthroughBehavior: when_no_match
                type: mock
      EndpointConfiguration:
        Type: REGIONAL
      Tags:
        Product: !Ref ProductTagValue
        System: !Ref SystemTagValue
        Environment: !Ref Environment
        Owner: !Ref OwnerTagValue
        Source: !Ref SourceTagValue
        CheckovRulesToSkip: CKV_AWS_120

  MockPublishingAPIAccessLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/apigateway/mock-publishing-api-access-logs/${Environment}"
      RetentionInDays: 14
      KmsKeyId: !GetAtt SecretsEncryptionKMSKey.Arn
      Tags:
        - Key: Product
          Value: !Ref ProductTagValue
        - Key: System
          Value: !Ref SystemTagValue
        - Key: Environment
          Value: !Ref Environment
        - Key: Owner
          Value: !Ref OwnerTagValue
        - Key: Source
          Value: !Ref SourceTagValue
    
  SecretsEncryptionKMSKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub "alias/${AWS::StackName}-SecretsEncryptionKMSKey"
      TargetKeyId: !Ref SecretsEncryptionKMSKey

  SecretsEncryptionKMSKey:
    Type: AWS::KMS::Key
    Properties:
      Description: >
        KMS key used to protect secret configuration values used across the platform.
        Required by roles who need to update config values.
      Enabled: true
      EnableKeyRotation: true
      KeyPolicy:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action:
              - kms:*
            Resource: "*"
          - Effect: Allow
            Principal:
              Service: !Sub "logs.amazonaws.com"
            Action:
              - "kms:*"
            Resource: "*"

  MockPublishingAPIEndpointParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: The HTTP URL of the mock Publishing API
      Name: !Sub "/${Environment}/APIGateway/MockPublishingAPI/Endpoint"
      Type: String
      Value: !Sub "https://${MockPublishingAPI}.execute-api.${AWS::Region}.amazonaws.com/${Environment}"
      Tags:
        Product: !Ref ProductTagValue
        System: !Ref SystemTagValue
        Environment: !Ref Environment
        Owner: !Ref OwnerTagValue
        Source: !Ref SourceTagValue

Outputs:
  MockPublishingAPIEndpoint:
    Description: The HTTP URL of the mock Publishing API
    Value: !Sub "https://${MockPublishingAPI}.execute-api.${AWS::Region}.amazonaws.com/${Environment}"
