AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Description: Platform Global Resources

Parameters:
  Environment:
    Description: The name of the environment to deploy to
    Type: String
    Default: dev
    AllowedValues:
      - "dev"
      - "build"
      - "staging"
      - "integration"
      - "production"
  ValidationDomain:
    Description: The account.gov.uk validation domain
    Type: String
    Default: account.gov.uk
  ProductTagValue:
    Description: Value for the Product Tag
    Type: String
    Default: GOV.UK Sign In
  SystemTagValue:
    Description: Value for the System Tag
    Type: String
    Default: Account Management
  OwnerTagValue:
    Description: Value for the Owner Tag
    Type: String
    Default: govuk-accounts-tech@digital.cabinet-office.gov.uk
  SourceTagValue:
    Description: Value for the Source Tag
    Type: String
    Default: govuk-one-login/di-accounts-infra/platform-global-resources/template.yaml

Mappings:
  PlatformConfiguration:
    dev:
      home: home.dev.account.gov.uk
    build:
      home: home.build.account.gov.uk
    staging:
      home: home.staging.account.gov.uk
    integration:
      home: home.integration.account.gov.uk
    production:
      home: home.account.gov.uk

Resources:
  #
  # DNS Certificate
  #

  HomeExternalCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Sub
        - "${DNSSUFFIX}"
        - DNSSUFFIX: !FindInMap [PlatformConfiguration, !Ref Environment, home]
      SubjectAlternativeNames:
        - !Sub
          - "*.${DNSSUFFIX}"
          - DNSSUFFIX:
              !FindInMap [PlatformConfiguration, !Ref Environment, home]
      DomainValidationOptions:
        - DomainName: !Sub
            - "${DNSSUFFIX}"
            - DNSSUFFIX:
                !FindInMap [PlatformConfiguration, !Ref Environment, home]
          ValidationDomain: !Ref ValidationDomain
      ValidationMethod: DNS
      Tags:
        - Key: Product
          Value: !Ref ProductTagValue
        - Key: System
          Value: !Ref SystemTagValue
        - Key: Environment
          Value: !Ref Environment
        - Key: Name
          Value: !Sub "${AWS::StackName}-HomeExternalCertificate"
        - Key: Owner
          Value: !Ref OwnerTagValue
        - Key: Source
          Value: !Ref SourceTagValue

Outputs:
  HomeCertificateARN:
    Description: The ARN of the Home domain certificate.
    Value: !Ref HomeExternalCertificate
