AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Description: Platform Global Resources

Parameters:
  Environment:
    Description: The name of the environment to deploy to
    Type: String
    Default: dev
    AllowedValues:
      - "dev"
      - "build"
      - "staging"
      - "integration"
      - "production"
  ValidationDomain:
    Description: The account.gov.uk validation domain
    Type: String
    Default: account.gov.uk
  ProductTagValue:
    Description: Value for the Product Tag
    Type: String
    Default: GOV.UK Sign In
  SystemTagValue:
    Description: Value for the System Tag
    Type: String
    Default: Account Management
  OwnerTagValue:
    Description: Value for the Owner Tag
    Type: String
    Default: govuk-accounts-tech@digital.cabinet-office.gov.uk
  SourceTagValue:
    Description: Value for the Source Tag
    Type: String
    Default: alphagov/di-accounts-infra/platform-global-resources/template.yaml

Conditions:
  IsExternal: !Or
    - !Equals [ !Ref Environment, production ]
    - !Equals [ !Ref Environment, integration ]
  IsInternal: !Or
    - !Equals [ !Ref Environment, dev ]
    - !Equals [ !Ref Environment, build ]
    - !Equals [ !Ref Environment, staging ]

Mappings:
  PlatformConfiguration:
    dev:
      home: home.dev.account.gov.uk
    build:
      home: home.build.account.gov.uk
    staging:
      home: home.staging.account.gov.uk
    integration:
      home: home.integration.account.gov.uk
    production:
      home: home.account.gov.uk

Resources:
  #
  # WAFv2 WebACL
  #


  WebACLInternal:
    Condition: IsInternal
    Type: AWS::WAFv2::WebACL
    Properties:
      Name: !Sub "${AWS::StackName}-WebACL"
      DefaultAction:
        Block: {}
      Scope: CLOUDFRONT
      Rules:
        # Optional rule set to restrict to GDS IP addresses.
        # See WAFv2GDSIPSet resource further on.
        - Name: GDSIPs
          Action:
            Allow: {}
          Priority: 10
          Statement:
            IPSetReferenceStatement:
              Arn: !GetAtt WAFv2GDSIPSet.Arn
          VisibilityConfig:
            CloudWatchMetricsEnabled: true
            MetricName: !Sub "${AWS::StackName}-WAFGDSIPhits"
            SampledRequestsEnabled: false
        - Name: AWS-AWMManagedRuleCommonRuleSet
          OverrideAction:
            Count: {}
          Priority: 20
          Statement:
            ManagedRuleGroupStatement:
              Name: AWSManagedRulesCommonRuleSet
              VendorName: AWS
          VisibilityConfig:
            CloudWatchMetricsEnabled: true
            MetricName: !Sub "${AWS::StackName}-AWSCRShits"
            SampledRequestsEnabled: false
        - Name: AWS-AWSManagedRulesKnownBadInputsRuleSet
          Priority: 30
          OverrideAction:
            None: {}
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesKnownBadInputsRuleSet
          VisibilityConfig:
            CloudWatchMetricsEnabled: true
            MetricName: !Sub "${AWS::StackName}-AWSKBIhits"
            SampledRequestsEnabled: false
      VisibilityConfig:
        CloudWatchMetricsEnabled: true
        MetricName: !Sub "${AWS::StackName}-WAFv2hits"
        SampledRequestsEnabled: false
      Tags:
        - Key: Product
          Value: !Ref ProductTagValue
        - Key: System
          Value: !Ref SystemTagValue
        - Key: Environment
          Value: !Ref Environment
        - Key: Name
          Value: !Sub "${AWS::StackName}-WAFv2"
        - Key: Owner
          Value: !Ref OwnerTagValue
        - Key: Source
          Value: !Ref SourceTagValue

  WebACLExternal:
    Condition: IsExternal
    Type: AWS::WAFv2::WebACL
    Properties:
      Name: !Sub "${AWS::StackName}-WebACL"
      DefaultAction:
        Allow: { }
      Scope: CLOUDFRONT
      Rules:
        - Name: AWS-AWMManagedRuleCommonRuleSet
          OverrideAction:
            None: { }
          Priority: 20
          Statement:
            ManagedRuleGroupStatement:
              Name: AWSManagedRulesCommonRuleSet
              VendorName: AWS
          VisibilityConfig:
            CloudWatchMetricsEnabled: true
            MetricName: !Sub "${AWS::StackName}-AWSCRShits"
            SampledRequestsEnabled: false
        - Name: AWS-AWSManagedRulesKnownBadInputsRuleSet
          Priority: 30
          OverrideAction:
            None: { }
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesKnownBadInputsRuleSet
          VisibilityConfig:
            CloudWatchMetricsEnabled: true
            MetricName: !Sub "${AWS::StackName}-AWSKBIhits"
            SampledRequestsEnabled: false
      VisibilityConfig:
        CloudWatchMetricsEnabled: true
        MetricName: !Sub "${AWS::StackName}-WAFv2hits"
        SampledRequestsEnabled: false
      Tags:
        - Key: Product
          Value: !Ref ProductTagValue
        - Key: System
          Value: !Ref SystemTagValue
        - Key: Environment
          Value: !Ref Environment
        - Key: Name
          Value: !Sub "${AWS::StackName}-WAFv2"
        - Key: Owner
          Value: !Ref OwnerTagValue
        - Key: Source
          Value: !Ref SourceTagValue

  # The IP address blocks below are referenced from here:
  # https://sites.google.com/a/digital.cabinet-office.gov.uk/gds/working-at-gds/gds-internal-it/gds-internal-it-network-public-ip-addresses
  WAFv2GDSIPSet:
    Type: AWS::WAFv2::IPSet
    Properties:
      Addresses:
        - "213.86.153.211/32"
        - "213.86.153.212/32"
        - "213.86.153.213/32"
        - "213.86.153.214/32"
        - "213.86.153.231/32"
        - "213.86.153.235/32"
        - "213.86.153.236/32"
        - "213.86.153.237/32"
        - "51.149.8.0/25"
        - "51.149.8.128/29"
      IPAddressVersion: IPV4
      Scope: CLOUDFRONT
      Tags:
        - Key: Product
          Value: !Ref ProductTagValue
        - Key: System
          Value: !Ref SystemTagValue
        - Key: Environment
          Value: !Ref Environment
        - Key: Name
          Value: !Sub "${AWS::StackName}-WAFv2GDSIPSet"
        - Key: Owner
          Value: !Ref OwnerTagValue
        - Key: Source
          Value: !Ref SourceTagValue

  WebACLLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "aws-waf-logs-${AWS::StackName}"
      RetentionInDays: 1
      KmsKeyId: !GetAtt WAFLoggingKmsKey.Arn
      Tags:
        - Key: Product
          Value: !Ref ProductTagValue
        - Key: System
          Value: !Ref SystemTagValue
        - Key: Environment
          Value: !Ref Environment
        - Key: Name
          Value: WebACLLogGroup
        - Key: Owner
          Value: !Ref OwnerTagValue
        - Key: Source
          Value: !Ref SourceTagValue

  WebACLLogs:
    Type: AWS::WAFv2::LoggingConfiguration
    DependsOn: WebACLLogGroup
    Properties:
      LogDestinationConfigs:
        - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:${WebACLLogGroup}"
      ResourceArn: !If [IsInternal, !GetAtt WebACLInternal.Arn, !GetAtt WebACLExternal.Arn]

  WebACLLogGroupCSLSSubscription:
    Type: AWS::Logs::SubscriptionFilter
    Properties:
      DestinationArn: "arn:aws:logs:eu-west-2:885513274347:destination:csls_cw_logs_destination_prodpython"
      FilterPattern: ""
      LogGroupName: !Ref WebACLLogGroup

  WAFLoggingKmsKey:
    Type: AWS::KMS::Key
    Properties:
      EnableKeyRotation: true
      KeyPolicy:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action:
              - kms:*
            Resource: "*"
          - Effect: Allow
            Principal:
              Service: !Sub "logs.${AWS::Region}.amazonaws.com"
            Action:
              - "kms:Encrypt*"
              - "kms:Decrypt*"
              - "kms:ReEncrypt*"
              - "kms:GenerateDataKey*"
              - "kms:Describe*"
            Resource:
              - "*"
            Condition:
              ArnLike:
                "kms:EncryptionContext:aws:logs:arn": !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*"
      Tags:
        - Key: Product
          Value: !Ref ProductTagValue
        - Key: System
          Value: !Ref SystemTagValue
        - Key: Environment
          Value: !Ref Environment
        - Key: Name
          Value: !Sub "${AWS::StackName}-WAFLoggingKmsKey"
        - Key: Owner
          Value: !Ref OwnerTagValue
        - Key: Source
          Value: !Ref SourceTagValue

  WAFLoggingKmsKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub "alias/${AWS::StackName}-WAFLoggingKmsKey"
      TargetKeyId: !GetAtt WAFLoggingKmsKey.Arn

  #
  # DNS Certificate
  #

  HomeExternalCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Sub
        - "${DNSSUFFIX}"
        - DNSSUFFIX: !FindInMap [ PlatformConfiguration, !Ref Environment, home ]
      SubjectAlternativeNames:
        - !Sub
          - "*.${DNSSUFFIX}"
          - DNSSUFFIX: !FindInMap [ PlatformConfiguration, !Ref Environment, home ]
      DomainValidationOptions:
        - DomainName: !Sub
            - "${DNSSUFFIX}"
            - DNSSUFFIX: !FindInMap [ PlatformConfiguration, !Ref Environment, home ]
          ValidationDomain: !Ref ValidationDomain
      ValidationMethod: DNS
      Tags:
        - Key: Product
          Value: !Ref ProductTagValue
        - Key: System
          Value: !Ref SystemTagValue
        - Key: Environment
          Value: !Ref Environment
        - Key: Name
          Value: !Sub "${AWS::StackName}-HomeExternalCertificate"
        - Key: Owner
          Value: !Ref OwnerTagValue
        - Key: Source
          Value: !Ref SourceTagValue


Outputs:
  WAFv2WebACLARN:
    Description: The ARN of the WAFv2 WebACL.
    Value: !If
      - IsExternal
      - !GetAtt WebACLExternal.Arn
      - !GetAtt WebACLInternal.Arn
  HomeCertificateARN:
    Description: The ARN of the Home domain certificate.
    Value: !Ref HomeExternalCertificate
