AWSTemplateFormatVersion: "2010-09-09"

Description: >-
  All the DNS Hosted Zones in the Accounts space.
Parameters:
  Environment:
    Description: The name of the environment to deploy to
    Type: String
    AllowedValues:
      - build
      - staging
      - integration
      - production

Conditions:
  IsProduction: !Equals [ !Ref Environment, production]

Resources:
  SettingsHostedZone:
    Type: AWS::Route53::HostedZone
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Name: !If
        - IsProduction
        - settings.account.gov.uk
        - !Sub settings.${Environment}.account.gov.uk

  SettingsHostedZoneSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Description: The ID of hosted zone for the settings domain
      Name: !Sub "/${Environment}/Platform/Route53/HostedZone/Settings"
      Type: String
      Value: !GetAtt SettingsHostedZone.Id

Outputs:
  SettingsHostedZoneNameServers:
    Value: !Join
          - ","
          - !GetAtt SettingsHostedZone.NameServers
    Export:
      Name: SettingsHostedZoneNameServers
  SettingsHostedZoneId:
    Value: !GetAtt SettingsHostedZone.Id
    Export:
      Name: SettingsHostedZoneId
