AWSTemplateFormatVersion: "2010-09-09"

Description: >-
  All the DNS Hosted Zones in the Accounts space.
Parameters:
  Environment:
    Description: The name of the environment to deploy to
    Type: String
    AllowedValues:
      - dev
      - build
      - staging
      - integration
      - production

Conditions:
  IsProduction: !Equals [!Ref Environment, production]

Resources:
  HomeHostedZone:
    Type: AWS::Route53::HostedZone
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Name: !If
        - IsProduction
        - home.account.gov.uk
        - !Sub home.${Environment}.account.gov.uk

  HomeHostedZoneSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Description: The ID of hosted zone for the home domain
      Name: !Sub "/${Environment}/Platform/Route53/HostedZone/Home"
      Type: String
      Value: !GetAtt HomeHostedZone.Id

  DmarcRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      Name: !If
        - IsProduction
        - _dmarc.home.account.gov.uk
        - !Sub _dmarc.home.${Environment}.account.gov.uk
      Type: TXT
      ResourceRecords:
        - '"v=DMARC1;p=reject;sp=reject;adkim=s;aspf=s"'
      HostedZoneId: !Ref HomeHostedZone

Outputs:
  HomeHostedZoneNameServers:
    Value: !Join
      - ","
      - !GetAtt HomeHostedZone.NameServers
    Export:
      Name: HomeHostedZoneNameServers
  HomeHostedZoneId:
    Value: !GetAtt HomeHostedZone.Id
    Export:
      Name: HomeHostedZoneId
